export const componentRoutes = {
  home: "/",
  brand: "/brand",
  customer: "/customer",
  discounts: "/discounts",
  employee: "/employee",
  guest_list: "/guest_list",
  harvest: "/harvest",
  inegration: "/inegration",
  inventory: "/inventory",
  lineage: "/lineage",
  payment: "/payment",
  plant: "/plant",
  preorder: "/preorder",
  pricing_tier: "/pricing_tier",
  producer: "/producer",
  product: "/product",
  product_category: "/product_category",
  referneced_data: "/referneced_data",
  reporting: "/reporting",
  room: "/room",
  size: "/size",
  strains: "/strains",
  table: "/table",
  tag: "/tag",
  transction: "/transction",
  util: "/util",
  vendor: "/vendor",
  waste: "/waste",
  register_adjustments: "register-adjustments",
  register_transactions: "register-transactions",
  cash_summary: "cash-summary",
  reporting_inventory: "reporting-inventory",
  loyalty_snapshot: "loyalty-snapshot",
  closing_report: "closing-report",

};
